--Query 1 Find the item that has minimum weight
select MIN(WEIGHT) from ITEMS;

--Query2 Find the different warehouses in “Pune”
SELECT c.CNAME , w.WNAME
FROM CITIES as c 
JOIN WAREHOUSES as w 
ON c.C_ID = w.C_ID
WHERE c.CNAME = 'Pune';

--Query3 Find the details of items ordered by a customer “Mr. Patil”.
SELECT CUSTOMER.CNAME, CUSTOMER.CUS_ID, ITEMS.COST , ITEMS.DESCRIPTION
FROM CUSTOMER
JOIN ORDERS ON ORDERS.CUS_ID = CUSTOMER.CUS_ID
JOIN ITEMS ON ITEMS.ITEM_ID = ORDERS.ITEM_ID
WHERE CUSTOMER.CNAME = 'Mr Patil';

--Query4 Find a Warehouse which has maximum stores.
SELECT WAREHOUSES.W_ID , WAREHOUSES.WNAME , COUNT(STORES.SID) as STORE_COUNT 
FROM WAREHOUSES 
JOIN STORES ON WAREHOUSES.W_ID = STORES.W_ID
GROUP BY WAREHOUSES.W_ID 
HAVING COUNT(STORES.SID) =
 ( SELECT MAX(STORE_COUNT) FROM 
 ( SELECT WAREHOUSES.W_ID , COUNT(STORES.SID) as STORE_COUNT
 FROM WAREHOUSES 
 JOIN STORES ON WAREHOUSES.W_ID = STORES.W_ID
 GROUP BY WAREHOUSES.W_ID) AS WAREHOUSE_STORES
 );
 
 --Query5 Find an item which is ordered for a minimum number of times.
 SELECT ORDERS.ITEM_ID , COUNT(ORDERS.ITEM_ID) as ORDER_COUNT
 FROM ORDERS 
 GROUP BY ORDERS.ITEM_ID
 HAVING COUNT(ORDERS.ITEM_ID) =
 ( SELECT MIN(ORDER_COUNT) 
 FROM 
 (  SELECT ORDERS.ITEM_ID ,COUNT(ORDERS.ITEM_ID) as ORDER_COUNT
 FROM ORDERS 
 GROUP BY ORDERS.ITEM_ID) as COUNTED_ITEMS);

--Query6 Find the detailed orders given by each customer.
SELECT ORDERS.ONO , CUSTOMER.CUS_ID , ORDERS.ITEM_ID  , ITEMS.WEIGHT , ITEMS.COST  , ITEMS.DESCRIPTION
FROM CUSTOMER
JOIN ORDERS ON ORDERS.CUS_ID = CUSTOMER.CUS_ID
JOIN ITEMS ON ITEMS.ITEM_ID = ORDERS.ITEM_ID;


